a = input('请输入你的名字')
print('我的名字是', a)
b = input('请输入你的年龄')
print('我', b, '岁了')
c = input('请输入你的学历')
print('我的学历是', c)
d = input('请输入你的电话号码')
print('我的电话号码是', d)
e = input('请输入你的住址')
print('我的住址是', e)
f = input('请输入你的喜好')
print('我的喜好是', f)
g = input('请输入你的性格特征')
print('我很', g)
h = input('请输入你家里有几口人')
print('我家里有', h, '口人')
i = input('请输入你家里有哪些人')
print('分别是', i)
j = input('请输入你的梦想')
print('我的梦想是', j)
